name: Build and Deploy
on:
  push:
    branches:
      - master
env:
  APP_NAME: HungarianAlgorithm
  VERSION: 2.3.4
  NUGET_HOST: https://www.nuget.org
  NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    concurrency:
      group: ${{ github.repository }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Build and Deploy
        shell: pwsh
        run: |
          dotnet build -c Release .\$env:APP_NAME.sln;
          if ($LastExitCode -ne 0)
          { 
              throw "error";
          };

          dotnet test .\.tests\Tests.$env:APP_NAME\Tests.$env:APP_NAME.csproj
          if ($LastExitCode -ne 0)
          { 
              throw "error";
          };

          dotnet pack --output nupkgs /p:PackageVersion=$env:VERSION;
          if ($LastExitCode -ne 0)
          { 
              throw "error";
          };

          dotnet nuget push nupkgs/$env:APP_NAME"."$env:VERSION.nupkg -s $env:NUGET_HOST -k $env:NUGET_APIKEY;
          dotnet nuget push nupkgs/$env:APP_NAME"."$env:VERSION.snupkg -s $env:NUGET_HOST -k $env:NUGET_APIKEY;

      - name: GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          body: |
            Version: ${{ env.VERSION }}
            Commit: ${{ github.sha }}
          artifacts: "nupkgs/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false